### ISSUE TITLE
Unintuitive ban duration argument

### ISSUE THREAD

**Issue by P03W** [ChatSift/AutoModerator#77]
I recently tried to ban someone for 1 month with `duration: 1 month` only to find the user banned for 1 minute instead, some simple parsing/conversion could go a long way here

**Comment by didinele** [comment]
Yeah. The format isn't documented, but I can confirm months are unsupported - as shown [here](https://github.com/ChatSift/AutoModerator/blob/main/libs/core/src/ms.ts#L5-L12).

This is something that we're looking into fixing - it's been roadmapped.

Also, I'd actually prefer you bring those things to me over Discord. I don't look at those issue tracker a whole lot, I mostly intend to use it for actual source code issues.

**Comment by P03W** [comment]
I was unable to find any discord contact listed anywhere, so I brought it up here

**Comment by didinele** [comment]
It's available on the site. https://discord.gg/tgZ2pSgXX

**Comment by P03W** [comment]
Ah, the button is only available on desktop it seems, on mobile it's inaccessible unless you enable desktop mode in the browser
