### ISSUE TITLE
Muted role perms setup

### ISSUE THREAD

**Issue by JetCrooked** [ChatSift/AutoModerator#95]
This is both a feature request and a bug report - the bug is that the bot resets muted overrides that are already denied, for example:
![image](https://user-images.githubusercontent.com/30682557/188306644-773f7ef3-62a6-45b5-b970-7384aaa38db4.png)
and the feature request is for the list of perms that can be denied using `/config-mutes update-role role: @Muted` to be expanded to include `Use Application Commands`, `Stream`, `Use Activities`, and `Request to Speak` (in addition to the current list of `Send Messages`, `Send Messages in Threads`, `Create Public Threads`, `Create Private Threads`, `Add Reactions`, `Connect`, and `Speak`)

**Comment by didinele** [comment]
Considering recent v3 progress, won't fix with v2. Keeping this issue open to ensure this is properly done in v3 to the extent that it's still relevant.

**Comment by didinele** [comment]
no longer relevant
